import { IAttributes as ISendEmailMessageActionAttributest } from '../action/transfer/send/message/email';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData {
    /**
     * Eメール送信アクション属性
     */
    actionAttributes: ISendEmailMessageActionAttributest;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.SendEmailMessage;
    data: IData;
}
/**
 * Eメール送信タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
